// Mocks generated by Mockito 5.4.6 from annotations
// in el_buen_sabor_app/test/unit/providers/mesa_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:el_buen_sabor_app/features/mesas/domain/models/mesa.dart'
    as _i4;
import 'package:el_buen_sabor_app/features/mesas/domain/repositories/mesa_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MesaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMesaRepository extends _i1.Mock implements _i2.MesaRepository {
  MockMesaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Mesa>> getMesas() => (super.noSuchMethod(
        Invocation.method(
          #getMesas,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Mesa>>.value(<_i4.Mesa>[]),
      ) as _i3.Future<List<_i4.Mesa>>);

  @override
  _i3.Future<void> abrirMesa(
    int? idMesa,
    int? idMozo,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #abrirMesa,
          [
            idMesa,
            idMozo,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cerrarMesa(int? idMesa) => (super.noSuchMethod(
        Invocation.method(
          #cerrarMesa,
          [idMesa],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
