// Mocks generated by Mockito 5.4.6 from annotations
// in el_buen_sabor_app/test/unit/providers/pedido_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:el_buen_sabor_app/features/pedidos/domain/models/pedido.dart'
    as _i4;
import 'package:el_buen_sabor_app/features/pedidos/domain/models/plato.dart'
    as _i5;
import 'package:el_buen_sabor_app/features/pedidos/domain/models/rubro_model.dart'
    as _i6;
import 'package:el_buen_sabor_app/features/pedidos/domain/repositories/pedido_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PedidoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPedidoRepository extends _i1.Mock implements _i2.PedidoRepository {
  MockPedidoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> insertPedido(
    String? mesaId,
    List<_i4.Pedido>? carrito,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertPedido,
          [
            mesaId,
            carrito,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.Pedido>> getPedidos() => (super.noSuchMethod(
        Invocation.method(
          #getPedidos,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Pedido>>.value(<_i4.Pedido>[]),
      ) as _i3.Future<List<_i4.Pedido>>);

  @override
  _i3.Future<List<_i5.Plato>> getMenu() => (super.noSuchMethod(
        Invocation.method(
          #getMenu,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Plato>>.value(<_i5.Plato>[]),
      ) as _i3.Future<List<_i5.Plato>>);

  @override
  _i3.Future<List<_i6.Rubro>> getRubros() => (super.noSuchMethod(
        Invocation.method(
          #getRubros,
          [],
        ),
        returnValue: _i3.Future<List<_i6.Rubro>>.value(<_i6.Rubro>[]),
      ) as _i3.Future<List<_i6.Rubro>>);

  @override
  _i3.Future<void> deletePedido(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePedido,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> modificarPedido(
    int? pedidoId,
    String? mesa,
    List<_i4.Pedido>? pedidoModificado,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #modificarPedido,
          [
            pedidoId,
            mesa,
            pedidoModificado,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateEstado(
    int? id,
    _i4.EstadoPedido? nuevoEstado,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEstado,
          [
            id,
            nuevoEstado,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
